---
- name: Check if a folder f1 is present. If not present create file1
  hosts: all
  tasks:  
    - name: Check for folder f1
      stat:  
       path: /home/ubuntu/f1
      register: a

    - name: Display output of the above module
      debug:  
       var: a

    - name: Create f1 fle if folder is not present
      file:  
       name: /home/ubuntu/f1
       state: touch
      when: a.stat.exists == false


...         
